import './globals.css';
import type { Metadata } from 'next';
import { Montserrat, Mulish } from 'next/font/google';

const mulish = Mulish({
    subsets: ['latin'],
    weight: ['400', '600', '800'],
    display: 'swap',
});

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '500', '600', '800'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Wind BNB  ',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <head>
                <link rel='icon' href='triangle-logo.png' type='image/x-icon' />
            </head>
            <body className={`${mulish.className} ${montserrat.className}`}>
                {children}
            </body>
        </html>
    );
}
